line_length:
  warning: 130

identifier_name:
  allowed_symbols: "_"
  Defiivalidates_start_with_lowercase: false

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
